### ISSUE TITLE
ClearType-style LCD rendering

### ISSUE THREAD

**Issue by andre-barata** [libsdl-org/SDL_ttf#131]
This is a request, if possible, to add support for ClearType-style LCD rendering, which FreeType already seems to [support](https://www.freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html).

This makes smaller font sizes more readable, by basically using the R G and B portions of every pixel as additional subpixels with [different luminance levels](https://en.wikipedia.org/wiki/Subpixel_rendering). 
![image](https://user-images.githubusercontent.com/6938680/120062621-0dbd5180-c05b-11eb-817e-40f4c9d70051.png)
 
maybe a new hinting type would be a good place to set the feature on. like :
`TTF_SetFontHinting(mainFont, TTF_HINTING_LCD_SUBPIXEL);`

**Comment by 1bsyl** [comment]
Did you try the subpixel rendering mode which is present in head source ?
https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.h#L141

which lcd hardware do you use ?

**Comment by andre-barata** [comment]
Yes, I'm currently using that mode on a [project](https://github.com/andre-barata/GridMerge/tree/3f91f46d9f9b38ea6ba9192ba9436428c9340189) with the latest version of SDL_ttf.
I'm using the new hint type `TTF_SetFontHinting(mainFont, TTF_HINTING_LIGHT_SUBPIXEL);`. 
The readability is better, but still not as good as with the colored edges on the fonts. here's an example:

![image](https://user-images.githubusercontent.com/6938680/120085395-b0171c80-c0cf-11eb-81b3-d362b8a41f21.png)

**Comment by 1bsyl** [comment]
I give a try and this seems almost feasible to add this rendering.
but that would only make sense with SDL *blended* function which returns an ARGB surface.

the thing is that blended, also require an argb color parameter 
https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.h#L284
and I am not sure how to blend the RGB glyph with this argb color parameter, any idea?

**Comment by 1bsyl** [comment]
Hi @andre-barata 
Here's an archive, can you give a try. [LCD.zip](https://github.com/libsdl-org/SDL_ttf/files/6597997/LCD.zip)
Either patch your SDL_ttf with the .diff file, or re-use the SDL_ttf.c/h files.

You need to set the hinting to LCD, use the TTF_*Blended functions to render text.

Still not sure how the blended color should be used. 
(currently best to draw in white, or bright, if you use black, it wont draw something correct)

**Comment by andre-barata** [comment]
Hi, i'm without access to a computer untill sunday. But i will try ir as soon as i get back. Thank you :)

**Comment by andre-barata** [comment]
also, i used the diff file because the .c and .h had some compilation errors

**Comment by andre-barata** [comment]
i was thinking a bit more on the correct way to blend the text with the background, with the blend modes that are supported with hardware and software acceleration... 

So considering an example where we have an edge of a font that fills red portion of the pixel and a background of gray:
**src1** = FF0000 (font)
**dest** = 888888 (gray background)
we would want the output to be: FF8888 right?
so we could do this:
![image](https://user-images.githubusercontent.com/6938680/122189322-c0c5e180-ce88-11eb-9096-bdc55c8f5bf8.png)
1. create a negative of source and save it to **src2** as a texture
2. multiply **dest** with **src2** using **SDL_BLENDMODE_MOD**
3. add **src1** to **dest** using **SDL_BLENDMODE_ADD**

so `output = src1 + dest * src2` where `src2 = 1 - src1`
this would take 2 blending operations, but since it would be most often done in the GPU, i think it should be fast

**Comment by 1bsyl** [comment]
@andre-barata yes the shaded version isn't meant to be used  with LCD rendering. (Shaded use a palette a format, and this won't work).


I looked at Free Type demos. to see how there were doing the LCD rendering blending :
https://www.freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html

"The described algorithms can completely remove color artefacts when
combined with gamma-corrected alpha blending in linear space. **Each of
the 3 alpha values (subpixels) must by independently used to blend one
color channel. That is, red alpha blends the red channel of the text
color with the red channel of the background pixel.**"

see screenshot: 

![Screenshot from 2021-06-16 11-18-34](https://user-images.githubusercontent.com/818728/122193379-ba3d6700-ce94-11eb-883c-2b4b680cd5ab.png)

![Screenshot from 2021-06-16 11-33-04](https://user-images.githubusercontent.com/818728/122195479-b0b4fe80-ce96-11eb-83aa-d8c01e60c11c.png)

command line is:
./bin/ftstring 12  some_font.ttf
F1: help
<space> change color
l : cycle through hinting

blending is done in _gblender_blit_hrgb_rgb32 :
https://gitlab.freedesktop.org/freetype/freetype-demos/-/blob/master/graph/gblany.h#L148

but it's precomputed here:
https://gitlab.freedesktop.org/freetype/freetype-demos/-/blob/master/graph/gblender.c#L195

the blending seems :
` r = ( r2 * a + r1 * ( 255 - a ) + 127 ) / 255;`

r1 = background channel
r2 = foreground channel
a = glyph channel (converted, it's only 4bits) 
r = is the outpout
we should ignore gamma level thing I guess.
channel means, independently, R, B, G)

In FT screenshot case foreground is RGB: 0 0 255
and background is 255 255 0 (but it's re-read, and maybe different if there are any overlap)

the SDL_ttf should also propose a background (ARGB) and foreground (RGB)  color for to render in LCD API. Which seems problematic with the blended API because it has only has 1 color  parameter ...
(btw, SDL_ttf, doesn't use the SDL_BLENDMODE flags )

**Comment by 1bsyl** [comment]
@andre-barata 
Here's a new version: 
Instead of using the hinting enum, I've added a new API to do the LCD rendering.
Please give a try

[LCD-v2.zip](https://github.com/libsdl-org/SDL_ttf/files/6683001/LCD-v2.zip)

```
/* Create a 32-bit surface (SDL_PIXELFORMAT_ARGB8888) and render the given text
   using FreeType LCD rendering, with the given font and colors.
   This function returns the new surface, or NULL if there was an error.
*/
extern DECLSPEC SDL_Surface * SDLCALL TTF_RenderText_LCD(TTF_Font *font,
                const char *text, SDL_Color fg, SDL_Color bg);
extern DECLSPEC SDL_Surface * SDLCALL TTF_RenderUTF8_LCD(TTF_Font *font,
                const char *text, SDL_Color fg, SDL_Color bg);
extern DECLSPEC SDL_Surface * SDLCALL TTF_RenderUNICODE_LCD(TTF_Font *font,
                const Uint16 *text, SDL_Color fg, SDL_Color bg);

and also the "Wrapped" versions
```

**Comment by andre-barata** [comment]
hi @1bsyl 

i'm getting a compilation error:
```
gcc  -std=c11 -Wno-unknown-pragmas -I/mingw64/include/SDL2 `pkg-config freetype2 --cflags`   -DUSE_FREETYPE  -DDEBUG -g -o obj/main.o -c src/main.c
gcc  -std=c11 -Wno-unknown-pragmas -I/mingw64/include/SDL2 `pkg-config freetype2 --cflags`   -DUSE_FREETYPE  -DDEBUG -g -o obj/include/thirdparty/SDL_ttf.o -c src/include/thirdparty/SDL_ttf.c
src/include/thirdparty/SDL_ttf.c: In function 'Render_Line':
src/include/thirdparty/SDL_ttf.c:1297:20: warning: implicit declaration of function 'Render_Line_SDF_LCD'; did you mean 'Render_Line_SSE_LCD'? [-Wimplicit-function-declaration]
 1297 |             return Render_Line_##NAME##_LCD(font, textbuf, xstart, ystart, &fg);                            \
      |                    ^~~~~~~~~~~~
src/include/thirdparty/SDL_ttf.c:1304:9: note: in expansion of macro 'Call_Specific_Render_Line'
 1304 |         Call_Specific_Render_Line(SDF)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
gcc  -std=c11 -Wno-unknown-pragmas -I/mingw64/include/SDL2 `pkg-config freetype2 --cflags`   -DUSE_FREETYPE  -DDEBUG -g -o GridMerge obj/opensans_regular.ttf.o obj/opensans_semibold.ttf.o obj/set10x10.png.o obj/main.o obj/include/thirdparty/SDL_ttf.o obj/winres.res  -LD:/Dev/msys64/mingw64/lib `sdl2-config --cflags --static-libs` -Wl,--whole-archive -lwinpthread -Wl,--no-whole-archive -lz -lbz2 -lpng16 -lz -lharfbuzz -lm -lusp10 -lgdi32 -lrpcrt4 -ldwrite -lglib-2.0 -lintl -lws2_32 -lole32 -lwinmm -lshlwapi -pthread -lm -lpcre -lbrotlidec-static -lbrotlicommon-static -lgraphite2 -lfreetype -lstdc++  -Wl,-subsystem,console
D:/Dev/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: obj/include/thirdparty/SDL_ttf.o: in function `Render_Line':
C:\Users\Andre\Dropbox\dev\gridMerge/src/include/thirdparty/SDL_ttf.c:1304: undefined reference to `Render_Line_SDF_LCD'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:91: GridMerge] Error 1
The terminal process "d:\dev\msys64\usr\bin\bash.exe '--login', '-i', '-c', 'make debug'" terminated with exit code: 2.
```
do i need to do any specific #define before including it?

**Comment by 1bsyl** [comment]
@andre-barata 
I forgot to test compilation when using SDF.
Add for the moment, line 1261:
`int (*Render_Line_SDF_LCD)() = NULL;`

**Comment by andre-barata** [comment]
this is looking amazing:
![image](https://user-images.githubusercontent.com/6938680/123268723-36b7f180-d4f6-11eb-8bcb-469230e94923.png)
It looks perfect on my LCD monitor:
![image](https://user-images.githubusercontent.com/6938680/123269880-4e43aa00-d4f7-11eb-99cb-1c24f70ee15c.png)

it's a shame that SDL_TTF doesn't use SDL_BLENDMODE  flags, because you wouldn't need to give it a background color, i did a few test's after my last post and got [it working](https://github.com/andre-barata/GridMerge/blob/7b71abb19d9a80fb57b0f1575d049757dc2ab919/src/include/view/font_stb.h#L230) with an alternate library (stb_truetype). however the text looks nicer with SDL_TTF, especially now with the LCD subpixels:
![image](https://user-images.githubusercontent.com/6938680/123271881-29e8cd00-d4f9-11eb-85a8-f18941db3012.png)
the stb_truetype version is however fast, because its using GPU blending, and a cache Font Atlas.

anyway i'm gonna keep support for both versions. 

I don't have other screen types to test it, but the changes you did should also work on some LCDs with different pixel geometry, i think.

Are you thinking on migrating your changes to the main branch?

Cheers

**Comment by 1bsyl** [comment]
Thanks for the feedback.

Freetype has a set of functions to customize the LCD rendering .. I just used the default, but for a specific LCD, maybe one should use a specific filter to render on a specific LCD hardware. But I've never tried that :  https://www.freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html#ft_library_setlcdfilter 

For the blendmode :
Maybe you can render on a black background (with alpha opaque (255), or maybe alpha transparent (0)), and blend the surface afterwards ?

This version is slow, because it uses LCD + subpixel positionning.
LCD : it splits the glyph on each the RGB channels, distinctly.
subpixel positionning: it renders at a subpixel position. for instant it you write "A" at position=0 or position=0.5 it won't be the same rendered 'A'.
it you render black (255) at 0, it renders a bitmap with pixel[0] = 255.
it you render black (255) at 0.5, it renders a bitmap with pixel[0] = 127, and pixel[1]=128.

So "subpixel positionning" needs each glyph to be re-rendered each time.

Not sure if the GPU can do that ... I mean it can position at sub pixel position, but is final text quality correct.
But, of course, it's faster!

Here's a new version that has both LCD, and LCD-subpixel (which is enabled if you set TTF_HINTING_LIGHT_SUBPIXEL).
If you don't use only LCD, glyph are cached in CPU memory.
[LCD-v3.zip](https://github.com/libsdl-org/SDL_ttf/files/6710184/LCD-v3.zip)

Don't know yet, it this is going to main branch, maybe:)

**Comment by andre-barata** [comment]
hi @1bsyl, 

yes, i could do that, render a grayscale bitmap and use it to do the transparent blending. its actually what i did with stb_freetype, because they don't provide any functions for using a specific graphics platform like SDL. its up to the developer.
they also don't support hinting, i think that's why the fonts look so different.

i see what you mean about subpixel positioning... on the other version i had to cache several samples for each subpixel position, which i went with 3... so basically with the subpixel positioning of 0; 0.33; 0.66. ideally i would have more than 3 samples to improve the quality, but that's more RAM usage, ant this way i got to use the same 3 samples i had for RGB.
i think even though the GPU can render at float positions, it would look blurred and just make pixels take up 2 spaces.

The LCD light subpixel hinting also looks great: 
![image](https://user-images.githubusercontent.com/6938680/123413471-ba331a80-d5aa-11eb-8bbc-152ce1aef4d0.png)

Cheers

**Comment by 1bsyl** [comment]
@andre-barata  ok!
Just to make clear, the previous v2.zip version, was already hard-coded LCD + subpixel positionning.
In the new version (in v3), you want to try (and check for speed) LCD, without setting any specific hinting (you can use hinting but not the subpixel_light hinting).
Then, it won't re-renderer glyph each time, and you should so some speed improvement.
(but the glyph positioning should be less good) 

Cheers

**Comment by andre-barata** [comment]
You're right, without using TTF_SetFontHinting(), the render is about 7 times faster than my GPU Blit loop, and with TTF_HINTING_LIGHT_SUBPIXEL its slightly slower than the GPU version.
so good news! we are talking about less than 9 milliseconds for like a 9 line paragraph of small text on my system without subpixel hinting :)

btw when you said CPU memory earlier, is that the CPU cache, like the static ram inside the CPU? i never knew a way to tell the compiler which type of memory to use Cache or RAM. i saw you were using some SIMD/SSE operations, is that how?

**Comment by 1bsyl** [comment]
@andre-barata ok great ! thank for the feeback

I mean the CPU memory (ram or caches.. that the CPU which chooses),   it's just not GPU memory.
what happens in SDL_ttf when you draw a string:
1/ We ask Freetype renders the chars (if there are not in cache). 
2/ if newly renderered, we save this rendered char in cache (array c code) 
3/ SDL_ttf blits all the needed char (from cache) to make the SDL_surface.

With subpixel, the 1/ must always be re-done to have the correct subpixel position. 
(actually, the subpixel offset is saved, so the cache can be re-used sometime, but rarely)

**Comment by 1bsyl** [comment]
@andre-barata,
I've created a PR, so it's easier to keep the patch up to date

**Comment by slouken** [comment]
This has been merged!
