### ISSUE TITLE
Add Bidi support

### ISSUE THREAD

**Issue by ericoporto** [libsdl-org/SDL_ttf#135]
This is for bidirectional text support in languages like Persian and Hebrew.

Fribidi has a license that may not be compatible with some platforms, so may be interesting to use ICU or [SheenBidi](https://github.com/Tehreer/SheenBidi) as alternatives instead.

[libraqm](https://github.com/HOST-Oman/libraqm) can either be used as reference or integrated. [Super Tux Kart has a fork of SDL_ttf](https://github.com/SuperTux/SDL_ttf) that appears to have Bidi support, but I think it's from before color emojis - no polar bears it seems.

**Comment by 1bsyl** [comment]
Persian and Hebrew are working if you enable SDL_ttf with Harfbuzz !
And you also need to call 
TTF_SetDirection()
TTF_SetScript()

**Comment by ericoporto** [comment]
Thanks, I am, but if you need numbers or other characters not from those than SetDirection will reverse those too. It's hard to wrap Bidi on the outside of SDL_ttf - like with SheenBidi.

**Comment by 1bsyl** [comment]
Reversing a sub-string inside a string isn't really a big deal.
At least, for a basic case: scan the string, detect latin char (being greedy) or stop / save start position/size and reverse in place.

I didn't search to add that in SDL_ttf, because a big issue (for me) is that SDL_ttf only uses 1 font at a time.
If you have a string AAABBB where A belong to A.ttf and B to B.ttf, you won't be able to render it fully (but with tofus).
A corner case, it that this can happen with RTL and LTR fonts, also probably intersecting a string that would have to be reversed. 
So, one need to scan a string anyway at a upper level, apply the bidi, split in parcels that can be rendered with1 font, and render with that font.

But, if you're interested, there is a patch that uses freebidi in SDL_ttf  (https://github.com/libsdl-org/SDL_ttf/issues/66 )... ok from the notification, I see that you already know it.

**Comment by khaledhosny** [comment]
Raqm support was provided years ago, long before the current HarfBuzz integration, and it supports RTL and other so-called complex scripts, but so far it has been ignored by SDL_ttf maintainer(s):
https://github.com/libsdl-org/SDL_ttf/issues/66

**Comment by 1bsyl** [comment]
Maybe re-base the patch. so people can use in SDL_ttf, while still being optional at compilation.
Also, I am not good to enough at RTL/LTR mixing rules, to see what it solves.

**Comment by khaledhosny** [comment]
If there is no indication that the patch will be reviewed and potentially merged, what would be the point of spending the effort in rebasing it?

**Comment by ericoporto** [comment]
if the patch was rebased though it would be possible to use it and have the current implementation with colored emojis, right? That would be useful to me at least.

**Comment by slouken** [comment]
Please feel free to submit a pull request and it will be reviewed after the 2.0.18 release.

Thanks!

**Comment by slouken** [comment]
There hasn't been any response, so I'm going ahead and closing this. Feel free to reopen it if you would like to submit a PR.
