### ISSUE TITLE
Release 2.0.16 ETA?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_ttf#142]
With SDL2 2.0.16 being released a few hours ago, and plenty of new additions to `SDL_ttf` since the last release in 2019, I was wondering whether there was a similar target release date for `SDL_ttf` 2.0.16? I maintain the Python bindings for SDL2 and its add-on libraries (ttf, image, mixer), so I'm just trying to get an idea of when I'll need to update my bindings to support the new set of functions.

Thanks in advance!

**Comment by ericoporto** [comment]
I think for this to be possible it would need to be set a milestone and the required issues to be created to track what is needed for such release.

**Comment by mil** [comment]
+1 asking for a 2.0.16 release due to bitmap fonts being broken with SDL_ttf 2.0.15 & latest freetype 2.11.  SDL_ttf's current release with latest freetype release using bitmap fonts is unusable so I think this would justify a new tag to re-enable this functionality.

For [my project](http://sr.ht/mil/mepo); we depend on SDL_ttf and use bitmap fonts for simplicity at the moment. Have had a few users raise this issue to me - that bitmap fonts in SDL_ttf are broken, and the only workaround is to downgrade freetype which is a bit of hack and difficult in our distribution (alpine).

**Comment by slouken** [comment]
Yes, a SDL_ttf release is on the way, thanks for the feedback!

**Comment by mil** [comment]
Great to hear a new SDL_ttf release is on the way. Out of curiosity is there some sort of expected timeframe for this release?

**Comment by slouken** [comment]
I’m planning to work on it after the SDL 2.0.18 release.

**Comment by ftphikari** [comment]
This is a personal request from the Odin language community, Odin has bindings for SDL_ttf of the current git version, but cannot use them on Linux because most Linux distros supply old version of SDL_ttf, even Arch.

Please make sure to release this ASAP, the latest release is already almost 3 years old and _32 functions are crucial for modern unicode handling.

**Comment by slouken** [comment]
Soon! :)

A pre-release is available here:
http://www.libsdl.org/tmp/SDL_ttf/

**Comment by a-hurst** [comment]
> Soon! :)
> 
> A pre-release is available here: http://www.libsdl.org/tmp/SDL_ttf/

Fantastic, thanks for keeping us posted (and for all your hard work)! Two questions:

1. Now that SDL\_ttf 2.0.18 is being prepared for release, are new releases of Mixer and Image next on the list?
2. Checking out the pre-release binaries you linked, I noticed that the macOS framework now seems to have FreeType built statically into the binary instead of being a separate sub-framework. Is that just a quirk of the pre-release, or is that how dependencies for ttf/image/mixer are going to be handled from now on?

**Comment by slouken** [comment]
> 1. Now that SDL_ttf 2.0.18 is being prepared for release, are new releases of Mixer and Image next on the list?

Yep!

> 2. Checking out the pre-release binaries you linked, I noticed that the macOS framework now seems to have FreeType built statically into the binary instead of being a separate sub-framework. Is that just a quirk of the pre-release, or is that how dependencies for ttf/image/mixer are going to be handled from now on?

This is a change specifically for SDL_ttf. FreeType is a required dependency, whereas the other libraries are optional format dependencies for the libraries.

**Comment by 1bsyl** [comment]
@slouken 
BTW :

- NEON is commented out whereas it works!
https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.c#L99

- TTF_SetDirection and TTF_SetScript request int as a parameter whereas this is a specific enum. is casting important here ?
  https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.h#L334

- There is an internal change with this version: 
 the text  SDL_Surface that are created are not tightly packed. eg ( `surface->pitch >  4 * surface->w` )
 (this way all line blit are simd aligned which is faster )
 It should be no problem, not sure if this matters.

- Currently android isn't building (see #156)

- Maybe this PR would be interesting: ClearType-style LCD rendering #138 but this can be delayed if more people want it

**Comment by sezero** [comment]
Looked at the temporary SDL2_ttf-2.0.18.tar.gz, a few minor notes:

- The autotools files differ from the git repo, namely aclocal.m4,
  Makefile.in and configure: I am guessing that `autoreconf` was
  run in the tree. The easy way of fixing the dates of the autofoo
  files is runing the `touch-autofoo.sh` script in the source tree.

- The tarball contains `CMakeLists.txt`, even though Makefile.am 
  doesn't have it in `EXTRA_DIST` list: fixed in git. (The thing
  with CMakeLists.txt is that it isn't mature yet - see the big fat
  FIXME notes in it.

**Comment by sezero** [comment]
@icculus, @slouken: About the latest 2.0.18 release here at github:
Having github source archive links isn't good for source releases. We
should add a proper release tarball as we used to: I can add one to
the existing release if you want me to.

**Comment by slouken** [comment]
I'm not opposed to that, but why is it needed?

**Comment by sezero** [comment]
- Download and look at the filename, then extract and look at the filename again.
- I remember that the archive tarballs aren't guaranteed to stay the same (Although
  I can't find the link for that as a proof.)
- The archive tarballs have every and all files with the date of the last commit they
  are tagged from, so: `./configure && make` will force an `autoreconf` and that's
  bad for business for people who don't have the same versions of autofoo (if they
  actually have them in the first place.)
- Others might have more arguments.

**Comment by slouken** [comment]
Fair enough. I've uploaded source archives and signatures for the SDL and SDL_ttf releases.

**Comment by slouken** [comment]
SDL_ttf is released!
