### ISSUE TITLE
What is the range of renderable glyphs? (Does it vary by font?)

### ISSUE THREAD

**Issue by edbird** [libsdl-org/SDL_ttf#149]
I am writing an application which uses SDL TTF.

I have currently loaded font Liberation Mono to do some testing with.

I have been able to render characters with values in the range of ' ' (space) to '~'.

I then wanted to include a block character in my application, which I thought I might be able to do by chosing to render a value from the extended ascii characters range. (See: https://www.asciitable.com/)

This didn't work, and resulted in some strange renderings. (See below.)

Hence my question becomes: What is the range of values which can be used to render valid characters? Is this universal between all fonts, or does it vary between fonts? Clearly the values between ' ' and '~' must be rendererable by all fonts, otherwise the "font" would not constitute a valid font? (Proabably?)

Secondary to this question is the following question: Is it possible to render a block character, or do I have to do this manually with other SDL functions. (For example rectangle rendering draw functions.)

![image](https://user-images.githubusercontent.com/2939755/135910975-7bada80d-ee7d-4ca7-8683-5b92df368b0f.png)

**Comment by 1bsyl** [comment]
The range varies between fonts.  There are fonts with alphabets, some other with emoji, and international fonts,  etc.

SDL_ttf provide no function to query ranges. Probably FreeType does.
But you can check if a glyph exist in the font with TTF_GlyphIsProvided
https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.h#L174

Otherwise, most of SDL_ttf are functions to render a block of characters.

**Comment by 1bsyl** [comment]
It sounds it should be a feature request. and / or TTF_GlyphIsProvided() exists. So just closing
