### ISSUE TITLE
libsdl page needs update

### ISSUE THREAD

**Issue by ftphikari** [libsdl-org/SDL_ttf#168]
https://www.libsdl.org/projects/SDL_ttf/

This page needs to be updated, documentation as well

**Comment by a-hurst** [comment]
I just recently ported the TTF (and image) docs over to Sphinxdoc format for the PySDL2 project, which involved a lot of extra rephrasing and argument documentation: https://pysdl2.readthedocs.io/en/latest/modules/sdl2_sdlttf.html

It's obviously not a drop-in replacement for the C docs since they're tuned specifically to the Python bindings, but if the libSDL people (or anyone else) want to adapt or borrow any of the work I've done redocumenting the module, I offer it freely to them (not that I'd have any right to do otherwise since it's based on their work).

**Comment by slouken** [comment]
Yes, we plan to migrate documentation to the new SDL wiki format, but that isn't done yet.
