### ISSUE TITLE
showfont segfaults in CI after 591eab7

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_ttf#209]
Since commit 591eab7 "Let SDL handle the alignment of surface pixels", `./showfont` is segfaulting in CI.

I think the problem might be that older versions of SDL, notably the one in Ubuntu 20.04 that the CI runs against, do not guarantee any particular alignment for surface data?

**Comment by slouken** [comment]
I checked and SDL 2.0.10 uses SDL_SIMDAlloc() for surface pixels. Is there a way to debug this on the CI machine?

**Comment by slouken** [comment]
When SSE2 instructions are available, SDL_ttf and SDL 2.0.10-current both choose alignment of 16. When SSE is not available, they both (now) choose alignment based on the size of void*. Clearly I've made some assumptions that are wrong, but I'm not seeing it.

I noticed that the previous code always added `alignment - 1` to the pitch. Is the line drawing code in SDL_ttf always going over the width of the surface? That could cause this issue, and be hidden by the previous implementation.

**Comment by 1bsyl** [comment]
@slouken 
yes the pitch is aligned https://github.com/libsdl-org/SDL_ttf/commit/591eab73f0577f0867580b8c361e4aadd4a11916#diff-ba876d8376dbe12da2856ef9df568a1687c32310d1bbbb4990b68917411ef90dL1429
so that each beginning of line line is aligned 
(because the TTF routines does SIMD on each lines)

**Comment by 1bsyl** [comment]
In addition to the pitch be aligned. (so that each beginning of line line is aligned)

There is also an extra ending padding of pitch. so that the width is rounded (ceil'ed) up to alignmemt.
because each glyph is stored as an aligned block.  (https://github.com/libsdl-org/SDL_ttf/blob/main/SDL_ttf.c#L2166) 
So that there is no corner case of last remaining pixel when blitting the glyph with SIMD :)
