### ISSUE TITLE
[Feature Request] Allow specifying the winding order of GPU indices

### ISSUE THREAD

**Issue by Beyley** [libsdl-org/SDL_ttf#437]
https://github.com/libsdl-org/SDL_ttf/blob/0ad0c2518be948300ed1e133741932f1ba2a4e7b/src/SDL_gpu_textengine.c#L667

The default order that SDL_ttf outputs is opposite to the rest of my pipeline, so i have to do a post-processing step over the returned indices for it to render correctly, which is quite wasteful, it would be nice if i could specify the winding order for SDL_ttf's GPU text engine

**Comment by slouken** [comment]
@captain0xff, can you take a look?

**Comment by captain0xff** [comment]
I have fixed the other two issues and will create a PR after addressing this issue. I am just confused regarding whether the option should be a setter/getter or a hint. Though none of the satellite libs seems to use hints. @slouken is there a reason for this? And is there a policy regarding whether something should be a hint or api call?

**Comment by slouken** [comment]
Typically we don't set global options in the library, since it might be used by two different pieces of code with different requirements. I think that's unlikely in this case though.

An option when creating the text engine seems like a reasonable approach to me...?

**Comment by captain0xff** [comment]
> An option when creating the text engine seems like a reasonable approach to me...?

This is a possible way but probably 95% of the users won't use it or even know its significance. That's why it feels a bit odd to force them to set an extra parameter while creating the text engine.
One thing we can do is have TTF_Set/GetGPUTextEngineVertexWindingOrder that takes the text engine as a parameter. And we can leave the default winding order as clockwise. This way the option isn't global, beginners won't be bothered by it and people who want to do culling can set it as per their choice.

**Comment by slouken** [comment]
Sounds good.
