### ISSUE TITLE
2.0.14 OS-X binary release is x86_64 only

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#68]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.13
**Reported for operating system, platform:** Mac OS X (All), x86

# Comments on the original bug report:

On 2016-06-23 08:43:16 +0000, Richard Russell wrote:

> The OS-X binary release (SDL2_ttf-2.0.14.dmg) is x86_64 only rather than a 32/64-bit universal binary.  Since SDL2 supports OS 10.6 (Snow Leopard), which runs on 32-bit Macs, and since some applications for later OS versions may need to be built as 32-bit (for example if they contain assembler code) there remains a need for a 32-bit binary for the foreseeable future.

On 2017-09-10 06:28:27 +0000, Sam Lantinga wrote:

> This will be fixed in the next release, thanks!

**Comment by a-hurst** [comment]
Just an update for the sake of the maintainers, I'm pretty sure the latest official SDL2 mac binaries are 64-bit only and have been since at least SDL 2.0.10.

That said, it would be nice for the official Mac binaries for the next release of SDL_\ttf to be universal x86\_64/ARM64 to natively support the latest macs!

**Comment by slouken** [comment]
The 2.0.18 release has x86_64 and arm64 binaries included.
